### ISSUE TITLE
Please add config example for jaeger-collector jaeger-agent

### ISSUE THREAD

**Issue by patsevanton** [jaegertracing/jaeger#1281]
Hello!
Please add config example for jaeger-collector jaeger-agent
Thanks!

**Comment by pavolloffay** [comment]
@patsevanton hi, does this https://www.jaegertracing.io/docs/1.8/deployment/ satisfy your requirements?

If not could you please be more specific what is hard to understand/missing so we can improve our docs.

**Comment by patsevanton** [comment]
@pavolloffay I read https://medium.com/jaegertracing/running-jaeger-agent-on-bare-metal-d1fc47d31fab
View  `example uses a YAMLconfiguration file located at /etc/jaeger-agent.yaml`
in
`ExecStart=/usr/local/bin/agent-linux --config-file=/etc/jaeger-agent.yaml`

But i cannot find example config-file (not Kubernetes config)

Where i can find example config-file for jaeger-collector jaeger-agent?
Thanks!

**Comment by pavolloffay** [comment]
The agent configurations are showed directly in the blog post 

For example the first one:
```
reporter:
  type: tchannel
  tchannel:
    host-port: jaeger-collector:14267
```

The collector configuration varies depending on the storage being used. Use our docs or help command to configure it.

**Comment by hichem3** [comment]
Hello, 
i have an issue with forwarding a nodejs application traces to jaeger UI through jenkins , can anyone help me with this ?
i get this error when building jenkins job to spin up docker container and run npm install then npm start:


(node:3992) UnhandledPromiseRejectionWarning: Error: error sending spans over HTTP: Error: connect ECONNREFUSED 127.0.0.1:16686
    at _sender.flush (/var/jenkins_home/workspace/jaeger/node_modules/@opentelemetry/exporter-jaeger/build/src/jaeger.js:151:35)
    at Function.invokeCallback (/var/jenkins_home/workspace/jaeger/node_modules/jaeger-client/dist/src/reporters/sender_utils.js:33:9)
    at ClientRequest.<anonymous> (/var/jenkins_home/workspace/jaeger/node_modules/jaeger-client/dist/src/reporters/http_sender.js:152:32)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:3992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by yurishkuro** [comment]
@hichem3 you are sending to the wrong port, see https://www.jaegertracing.io/docs/1.23/deployment/

**Comment by hichem3** [comment]
@yurishkuro thank you for your fast answer , but that part of the port is the not the issue because whatever port i put it's the same error , it was 14250 same error , 14286 same error..

**Comment by hichem3** [comment]
(node:4773) UnhandledPromiseRejectionWarning: Error: error sending spans over HTTP: Error: connect ECONNREFUSED 127.0.0.1:14268
    at _sender.flush (/var/jenkins_home/workspace/jaeger/node_modules/@opentelemetry/exporter-jaeger/build/src/jaeger.js:151:35)
    at Function.invokeCallback (/var/jenkins_home/workspace/jaeger/node_modules/jaeger-client/dist/src/reporters/sender_utils.js:33:9)
    at ClientRequest.<anonymous> (/var/jenkins_home/workspace/jaeger/node_modules/jaeger-client/dist/src/reporters/http_sender.js:152:32)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:4773) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4773) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
