### ISSUE TITLE
Unstable test TestSaramaConsumerWrapper_start_Messages

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1462]
https://travis-ci.org/jaegertracing/jaeger/jobs/516359880#L1076
```
=== RUN   TestSaramaConsumerWrapper_start_Messages
2019-04-05T20:20:05.815Z	DEBUG	consumer/deadlock_detector.go:151	Starting global deadlock detector
2019-04-05T20:20:05.815Z	INFO	consumer/consumer.go:77	Starting main loop
2019-04-05T20:20:05.816Z	INFO	consumer/consumer.go:111	Starting message handler	{"partition": 316}
2019-04-05T20:20:05.816Z	DEBUG	consumer/consumer.go:134	Got msg	{"msg": {"Key":null,"Value":null,"Topic":"morekuzambu","Partition":316,"Offset":1,"Timestamp":"0001-01-01T00:00:00Z","BlockTimestamp":"0001-01-01T00:00:00Z","Headers":null}}
2019-04-05T20:20:05.817Z	INFO	consumer/processor_factory.go:62	Creating new processors	{"partition": 316}
2019-04-05T20:20:05.817Z	DEBUG	processor/parallel_processor.go:50	Spawning goroutines to process messages	{"num_routines": 1}
2019-04-05T20:20:05.818Z	INFO	consumer/consumer.go:162	Starting error handler	{"partition": 316}
2019-04-05T20:20:05.818Z	INFO	consumer/consumer.go:155	Closing partition consumer	{"partition": 316}
2019-04-05T20:20:05.818Z	INFO	consumer/consumer.go:131	Message channel closed. 	{"partition": 316}
2019-04-05T20:20:05.818Z	DEBUG	processor/parallel_processor.go:75	Initiated shutdown of processor goroutines
2019-04-05T20:20:05.818Z	INFO	consumer/consumer.go:158	Closed partition consumer	{"partition": 316}
2019-04-05T20:20:05.819Z	INFO	processor/parallel_processor.go:78	Completed shutdown of processor goroutines
2019-04-05T20:20:05.819Z	DEBUG	consumer/deadlock_detector.go:195	Closing deadlock detector	{"partition": 316}
2019-04-05T20:20:05.819Z	INFO	consumer/deadlock_detector.go:115	Closing ticker routine	{"partition": 316}
2019-04-05T20:20:05.819Z	INFO	consumer/consumer.go:155	Closing partition consumer	{"partition": 316}
2019-04-05T20:20:05.819Z	INFO	consumer/consumer.go:158	Closed partition consumer	{"partition": 316}
2019-04-05T20:20:08.816Z	PANIC	consumer/deadlock_detector.go:71	No messages processed in the last check interval	{"partition": -1, "stack": "goroutine 24 [running]:\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.newDeadlockDetector.func1(0xc0ffffffff)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:73 +0x2d4\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start.func1(0xc000164bd8, 0xc0001703e0)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:163 +0x288\ncreated by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:152 +0x346\n\ngoroutine 1 [chan receive]:\ntesting.(*T).Run(0xc0000b4400, 0xfb6220, 0x28, 0xfc9810, 0x1)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:917 +0x693\ntesting.runTests.func1(0xc0000b4400)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:1157 +0xa9\ntesting.tRunner(0xc0000b4400, 0xc000117d48)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:865 +0x164\ntesting.runTests(0xc00000ef40, 0x18b55a0, 0x15, 0x15, 0x0)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:1155 +0x524\ntesting.(*M).Run(0xc000102200, 0x0)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:1072 +0x2ec\nmain.main()\n\t_testmain.go:140 +0x335\n\ngoroutine 23 [semacquire]:\nsync.runtime_Semacquire(0xc000170528)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/sema.go:56 +0x39\nsync.(*WaitGroup).Wait(0xc000170520)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/sync/waitgroup.go:130 +0xb2\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Close(0xc000164b60, 0xc000156400, 0xe9d480)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:102 +0x175\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.TestSaramaConsumerWrapper_start_Messages(0xc000156400)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer_test.go:165 +0xb1e\ntesting.tRunner(0xc000156400, 0xfc9810)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:865 +0x164\ncreated by testing.(*T).Run\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:916 +0x65b\n\ngoroutine 25 [chan receive]:\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start.func1(0xc000164b60)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:78 +0x289\ncreated by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:76 +0x79\n\ngoroutine 28 [semacquire]:\nsync.runtime_SemacquireMutex(0xc000164c14, 0x900000000)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/sema.go:71 +0x3d\nsync.(*Mutex).Lock(0xc000164c10)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/sync/mutex.go:134 +0x1e2\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).handleErrors(0xc000164b60, 0x13c, 0xc000154720)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:163 +0x1ce\ncreated by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:92 +0x26b\n"}
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.newDeadlockDetector.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:71
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:163
panic: No messages processed in the last check interval
goroutine 24 [running]:
github.com/jaegertracing/jaeger/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000146e70, 0xc000102280, 0x2, 0x2)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x70f
github.com/jaegertracing/jaeger/vendor/go.uber.org/zap.(*Logger).Panic(0xc000086300, 0xfbbbcd, 0x30, 0xc000102280, 0x2, 0x2)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/go.uber.org/zap/logger.go:225 +0x96
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.newDeadlockDetector.func1(0xc0ffffffff)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:71 +0x4d8
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start.func1(0xc000164bd8, 0xc0001703e0)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:163 +0x288
created by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:152 +0x346
FAIL	github.com/jaegertracing/jaeger/cmd/ingester/app/consumer	3.025s
make: *** [cover] Error 1
The command "if [ "$TESTS" == true ]; then make test-ci ; else echo 'skipping tests'; fi" exited with 2.
```

**Comment by p0larstern** [comment]
I would like to help with this issue since it is for beginners, I am new to contributing and might need some help.

**Comment by yurishkuro** [comment]
Duplicate of #1314
