### ISSUE TITLE
Building jaeger-es-index-cleaner image fails

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1494]
https://github.com/jaegertracing/jaeger/pull/1492#issuecomment-486403209

```
    Searching for urllib3>=1.21.1
    Reading https://pypi.org/simple/urllib3/
    Downloading https://files.pythonhosted.org/packages/c0/1f/516c14fd47ced1a2e2882edd776241c5b707ffc9051cd372843579829994/urllib3-1.25.1-py2.py3-none-any.whl#sha256=a9645efd62b9fc1c7cad8ed93e162aad4c6bfd90e143966ddd4099b78cd244be
    Best match: urllib3 1.25.1
    Processing urllib3-1.25.1-py2.py3-none-any.whl
    Installing urllib3-1.25.1-py2.py3-none-any.whl to /tmp/pip-install-l6fu_uma/elasticsearch-curator/.eggs
    writing requirements to /tmp/pip-install-l6fu_uma/elasticsearch-curator/.eggs/urllib3-1.25.1-py3.7.egg/EGG-INFO/requires.txt

    Installed /tmp/pip-install-l6fu_uma/elasticsearch-curator/.eggs/urllib3-1.25.1-py3.7.egg
    Traceback (most recent call last):
      File "/tmp/pip-install-l6fu_uma/elasticsearch-curator/setup.py", line 37, in <module>
        from cx_Freeze import setup, Executable
    ModuleNotFoundError: No module named 'cx_Freeze'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l6fu_uma/elasticsearch-curator/setup.py", line 173, in <module>
        tests_require = ["mock", "nose", "coverage", "nosexcover"]
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 779, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.ContextualVersionConflict: (urllib3 1.25.1 (/tmp/pip-install-l6fu_uma/elasticsearch-curator/.eggs/urllib3-1.25.1-py3.7.egg), Requirement.parse('urllib3<1.25,>=1.21.1'), {'requests'})
```

**Comment by pavolloffay** [comment]
It does not seem to fix the problem

Now it fails with
```
make docker-images-elastic                                                                                                                                           1:46 
docker build -t jaegertracing/jaeger-es-index-cleaner:latest plugin/storage/es
Sending build context to Docker daemon  241.2kB
Step 1/5 : FROM python:3-alpine
 ---> 930a7e894675
Step 2/5 : RUN pip install urllib3==1.21.1
 ---> Running in 520fbe526e19
Collecting urllib3==1.21.1
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f20b611c550>: Failed to establish a new connection: [Errno -3] Try again')': /simple/urllib3/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f20b621fa50>: Failed to establish a new connection: [Errno -3] Try again')': /simple/urllib3/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f20b612dd10>: Failed to establish a new connection: [Errno -3] Try again')': /simple/urllib3/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f20b612d9d0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/urllib3/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f20b612d350>: Failed to establish a new connection: [Errno -3] Try again')': /simple/urllib3/
  ERROR: Could not find a version that satisfies the requirement urllib3==1.21.1 (from versions: none)
ERROR: No matching distribution found for urllib3==1.21.1
The command '/bin/sh -c pip install urllib3==1.21.1' returned a non-zero code: 1
make: *** [Makefile:248: docker-images-elastic] Error 
```

**Comment by Jaycean** [comment]
@pavolloffay I encountered the same mistake
- operating system： centos7  arm64
```
ocker build -t jaegertracing/jaeger-es-index-cleaner:latest plugin/storage/es
Sending build context to Docker daemon  249.9kB
Step 1/5 : FROM python:3-alpine
 ---> f8a57363ff96
Step 2/5 : RUN pip install urllib3==1.24.1
 ---> Running in a7fdabed2d73
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c pip install urllib3==1.24.1' returned a non-zero code: 1
make: *** [docker-images-elastic] 错误 1
```

- Changing the fixed version can't be solved

**Comment by Jaycean** [comment]
- The problem has been solved
- Because python:3-alpine There is no arm64 architecture in dockerhub, so I created one by myself using dockerfile

**Comment by pavolloffay** [comment]
thanks for reporting back @Jaycean! 

Just for curiosity why are you building arm64 image?

**Comment by Jaycean** [comment]
@pavolloffay 
- The company's business development needs, using x86 and arm64 two kinds of architecture
