### ISSUE TITLE
Jaeger CDI throws ClassCastException

### ISSUE THREAD

**Issue by sherwoodzern** [jaegertracing/jaeger#1526]
## Requirement - what kind of business use case are you trying to solve?

I'm deploying to a K8S cluster that has the Istio service mesh deployed. I want to attach to the tracer from Istio. 

## Problem - what in Jaeger blocks you from solving the requirement?

In my code I use CDI. I @Inject Tracer and even attempt to @Inject Span. I always receive the error: org.jboss.weld.exceptions.DeploymentException: 
WELD-001408: Unsatisfied dependencies for type Span with qualifiers @Default
  at injection point [BackedAnnotatedField] when attempting inject Span.  I remove the inject of Span.

I get the following exception at Runtime:
java.lang.ClassCastException: io.opentracing.propagation.TextMapExtractAdapter cannot be cast to io.opentracing.propagation.TextMap
	at io.jaegertracing.internal.propagation.TextMapCodec.extract(TextMapCodec.java:37)
	at io.jaegertracing.internal.PropagationRegistry$ExceptionCatchingExtractorDecorator.extract(PropagationRegistry.java:57)
	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:217)
	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:63)
	at io.opentracing.util.GlobalTracer.extract(GlobalTracer.java:204)
	at io.helidon.webserver.RequestRouting.createRequestSpan(RequestRouting.java:133)
	at io.helidon.webserver.RequestRouting.route(RequestRouting.java:71)
	at io.helidon.webserver.netty.ForwardingHandler.channelRead0(ForwardingHandler.java:130)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2019.05.08 19:16:21 INFO io.jaegertracing.internal.reporters.LoggingReporter Thread[nioEventLoopGroup-3-1,10,main]: Span reported: a8f85fa58ac64703:5074a743bcf3be8:a8f85fa58ac64703:1 - content-read

My code has the following:

Span parentSpan = tracer.activeSpan();
 Span span;
       
 if (parentSpan != null) {
            span = tracer.buildSpan("getDefaultMessage").asChildOf(parentSpan.context()).start();
        }
        else {
            
            span = tracer.buildSpan("getDefaultMessage").start();

        }

...
span.finish()

I would like to know what the ClassCastException. This is all of JaegerTracing and opentracing CDI code.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Get rid of the ClassCastException

**Comment by yurishkuro** [comment]
moving this to Java client repo
