### ISSUE TITLE
Elasticsearch docker images build failure

### ISSUE THREAD

**Issue by radekg** [jaegertracing/jaeger#1725]
I was building fresh images using the 1.13.1 release. While building docker images for elasticsearch (`make docker-images-elastic`), I experienced the following error:

```
Step 3/5 : RUN pip install elasticsearch elasticsearch-curator
 ---> Running in 6af4f5500721
Collecting elasticsearch
  Downloading https://files.pythonhosted.org/packages/ae/43/38329621bcca6f0b97e1cc36fb3cef889414a1960fcdc83a41e26b496634/elasticsearch-7.0.2-py2.py3-none-any.whl (83kB)
Collecting elasticsearch-curator
  Downloading https://files.pythonhosted.org/packages/18/12/b47c869f538f2d8c5766358288d8b5e0e6f27b34ed7131f8ccf18d2f396c/elasticsearch-curator-5.7.6.tar.gz (218kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zlkqritl/elasticsearch-curator/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zlkqritl/elasticsearch-curator/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-zlkqritl/elasticsearch-curator/
    Complete output (117 lines):

    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
    zip_safe flag not set; analyzing archive contents...

    Installed /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/PyYAML-3.12-py3.7-linux-x86_64.egg
    Searching for click<7.0,>=6.7
    Reading https://pypi.org/simple/click/
    Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl#sha256=29f99fc6125fbc931b758dc053b3114e55c77a6e4c6c3a2674a2dc986016381d
    Best match: click 6.7
    Processing click-6.7-py2.py3-none-any.whl
    Installing click-6.7-py2.py3-none-any.whl to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs

    Installed /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/click-6.7-py3.7.egg
    Searching for requests_aws4auth>=0.9
    Reading https://pypi.org/simple/requests_aws4auth/
    Downloading https://files.pythonhosted.org/packages/a4/4e/29ac240bff356eb630bcc729da7cdce6f55f21c442af325ca60dd27d4a3f/requests_aws4auth-0.9-py2.py3-none-any.whl#sha256=e20e4941ccd5706973068f9214d40cb2e669461536b3a57b9ac824ae87744c2c
    Best match: requests-aws4auth 0.9
    Processing requests_aws4auth-0.9-py2.py3-none-any.whl
    Installing requests_aws4auth-0.9-py2.py3-none-any.whl to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs
    writing requirements to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/requests_aws4auth-0.9-py3.7.egg/EGG-INFO/requires.txt

    Installed /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/requests_aws4auth-0.9-py3.7.egg
    Searching for boto3>=1.9.142
    Reading https://pypi.org/simple/boto3/
    Downloading https://files.pythonhosted.org/packages/05/90/f9d70a9e0d3f5d9d6fe634b9cf8c17a8fd42ee3ceffbb82a357df16f7e61/boto3-1.9.204-py2.py3-none-any.whl#sha256=3ec5b520dbd0a430cdd581a8250991fb0f21ee7e668a8928f15006b312fa86dc
    Best match: boto3 1.9.204
    Processing boto3-1.9.204-py2.py3-none-any.whl
    Installing boto3-1.9.204-py2.py3-none-any.whl to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs
    writing requirements to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/boto3-1.9.204-py3.7.egg/EGG-INFO/requires.txt

    Installed /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/boto3-1.9.204-py3.7.egg
    Searching for requests>=2.20.0
    Reading https://pypi.org/simple/requests/
    Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl#sha256=9cf5292fcd0f598c671cfc1e0d7d1a7f13bb8085e9a590f48c010551dc6c4b31
    Best match: requests 2.22.0
    Processing requests-2.22.0-py2.py3-none-any.whl
    Installing requests-2.22.0-py2.py3-none-any.whl to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs
    writing requirements to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/requests-2.22.0-py3.7.egg/EGG-INFO/requires.txt

    Installed /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/requests-2.22.0-py3.7.egg
    Searching for urllib3<1.25,>=1.24.2
    Reading https://pypi.org/simple/urllib3/
    Downloading https://files.pythonhosted.org/packages/01/11/525b02e4acc0c747de8b6ccdab376331597c569c42ea66ab0a1dbd36eca2/urllib3-1.24.3-py2.py3-none-any.whl#sha256=a637e5fae88995b256e3409dc4d52c2e2e0ba32c42a6365fee8bbd2238de3cfb
    Best match: urllib3 1.24.3
    Processing urllib3-1.24.3-py2.py3-none-any.whl
    Installing urllib3-1.24.3-py2.py3-none-any.whl to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs
    writing requirements to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/urllib3-1.24.3-py3.7.egg/EGG-INFO/requires.txt

    Installed /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/urllib3-1.24.3-py3.7.egg
    Searching for elasticsearch<8.0.0,>=7.0.0
    Reading https://pypi.org/simple/elasticsearch/
    Downloading https://files.pythonhosted.org/packages/ae/43/38329621bcca6f0b97e1cc36fb3cef889414a1960fcdc83a41e26b496634/elasticsearch-7.0.2-py2.py3-none-any.whl#sha256=d1b176b87a7fb75dca82978c82a4023e8b21cbc98f4018cb51190fb0b8b43764
    Best match: elasticsearch 7.0.2
    Processing elasticsearch-7.0.2-py2.py3-none-any.whl
    Installing elasticsearch-7.0.2-py2.py3-none-any.whl to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs
    writing requirements to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/elasticsearch-7.0.2-py3.7.egg/EGG-INFO/requires.txt

    Installed /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/elasticsearch-7.0.2-py3.7.egg
    Searching for voluptuous>=0.9.3
    Reading https://pypi.org/simple/voluptuous/
    Downloading https://files.pythonhosted.org/packages/59/95/fa6218477c6999c9b7fdfab7c12c1bd4da2d5930f5eb2b232ec74eb344e7/voluptuous-0.11.5-py2.py3-none-any.whl#sha256=303542b3fc07fb52ec3d7a1c614b329cdbee13a9d681935353d8ea56a7bfa9f1
    Best match: voluptuous 0.11.5
    Processing voluptuous-0.11.5-py2.py3-none-any.whl
    Installing voluptuous-0.11.5-py2.py3-none-any.whl to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs

    Installed /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/voluptuous-0.11.5-py3.7.egg
    Searching for s3transfer<0.3.0,>=0.2.0
    Reading https://pypi.org/simple/s3transfer/
    Downloading https://files.pythonhosted.org/packages/16/8a/1fc3dba0c4923c2a76e1ff0d52b305c44606da63f718d14d3231e21c51b0/s3transfer-0.2.1-py2.py3-none-any.whl#sha256=b780f2411b824cb541dbcd2c713d0cb61c7d1bcadae204cdddda2b35cef493ba
    Best match: s3transfer 0.2.1
    Processing s3transfer-0.2.1-py2.py3-none-any.whl
    Installing s3transfer-0.2.1-py2.py3-none-any.whl to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs
    writing requirements to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/s3transfer-0.2.1-py3.7.egg/EGG-INFO/requires.txt

    Installed /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/s3transfer-0.2.1-py3.7.egg
    Searching for jmespath<1.0.0,>=0.7.1
    Reading https://pypi.org/simple/jmespath/
    Downloading https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl#sha256=3720a4b1bd659dd2eecad0666459b9788813e032b83e7ba58578e48254e0a0e6
    Best match: jmespath 0.9.4
    Processing jmespath-0.9.4-py2.py3-none-any.whl
    Installing jmespath-0.9.4-py2.py3-none-any.whl to /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs

    Installed /tmp/pip-install-zlkqritl/elasticsearch-curator/.eggs/jmespath-0.9.4-py3.7.egg
    Searching for botocore<1.13.0,>=1.12.204
    Reading https://pypi.org/simple/botocore/
    No local packages or working download links found for botocore<1.13.0,>=1.12.204
    Traceback (most recent call last):
      File "/tmp/pip-install-zlkqritl/elasticsearch-curator/setup.py", line 39, in <module>
        from cx_Freeze import setup, Executable
    ModuleNotFoundError: No module named 'cx_Freeze'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zlkqritl/elasticsearch-curator/setup.py", line 175, in <module>
        tests_require = ["mock", "nose", "coverage", "nosexcover"]
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('botocore<1.13.0,>=1.12.204')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I believe this is because the pip dependencies are not pinned. When I change in both docker files under `plugin/storage/es`:

```
RUN pip install elasticsearch elasticsearch-curator
```

to

```
RUN pip install elasticsearch==7.0.2 elasticsearch-curator==5.7.2
```

the error disappears. The most recent curator version `5.7.6` does not appear to work. Forcing the lower version helps. However, the `urlib3` version needs to be bumped to `1.24.1`, as per warning with forced curator:

```
ERROR: elasticsearch-curator 5.7.2 has requirement urllib3==1.24.1, but you'll have urllib3 1.21.1 which is incompatible.
```

It would be great if all dependencies have been pinned at exact versions.

**Comment by yurishkuro** [comment]
would like like to create a pull request?  Dockerfiles are in plugin/storage/es

**Comment by pavolloffay** [comment]
Was fixed in https://github.com/jaegertracing/jaeger/pull/1495
