### ISSUE TITLE
Unstable test pkg/queue/TestResizeOldQueueIsDrained

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#1997]
cc @jpkrohling 

```
=== RUN   TestResizeOldQueueIsDrained
dropped: d
--- FAIL: TestResizeOldQueueIsDrained (0.00s)
panic: sync: negative WaitGroup counter
goroutine 12 [running]:
sync.(*WaitGroup).Add(0xc000370c60, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/sync/waitgroup.go:74 +0x22f
sync.(*WaitGroup).Done(...)
	/home/travis/.gimme/versions/go1.13.5.linux.amd64/src/sync/waitgroup.go:99
github.com/jaegertracing/jaeger/pkg/queue.TestResizeOldQueueIsDrained.func2(0x8591e0, 0x94d700)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue_test.go:276 +0x96
github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1(0xc000370c80, 0xc000012b00, 0xc00038b8c0)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:71 +0x11c
created by github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:63 +0x190
FAIL	github.com/jaegertracing/jaeger/pkg/queue	0.057s
FAIL
make: *** [cover] Error 1
```

**Comment by jpkrohling** [comment]
Oops. I'm on it.
