### ISSUE TITLE
Panic on close of closed channel

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2094]
The following happens when stopping the all-in-one when badger is being used as storage, probably related to #2076:

```console
$ SPAN_STORAGE_TYPE=badger go run -tags ui ./cmd/all-in-one 
...
^C{"level":"info","ts":1582817948.1366558,"caller":"flags/service.go:145","msg":"Shutting down"}
{"level":"info","ts":1582817948.1367006,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"unavailable"}
{"level":"info","ts":1582817948.136725,"caller":"app/agent.go:89","msg":"shutting down agent's HTTP server","addr":"[::]:5778"}
{"level":"info","ts":1582817948.136871,"caller":"app/agent.go:73","msg":"agent's http server exiting"}
{"level":"info","ts":1582817948.1374054,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"unavailable"}
panic: close of closed channel

goroutine 1 [running]:
github.com/jaegertracing/jaeger/plugin/storage/badger.(*Factory).Close(0xc0001a0180, 0x1df6d01, 0x7f6ba409f120)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/plugin/storage/badger/factory.go:167 +0x33
github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore.(*SpanWriter).Close(0xc0003b5a40, 0x1df49a0, 0xc0003b5a40)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore/writer.go:197 +0x34
main.main.func1.1()
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:156 +0x123
github.com/jaegertracing/jaeger/cmd/flags.(*Service).RunAndThen(0xc00005a980, 0xc0003219a0)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/cmd/flags/service.go:149 +0x1f6
main.main.func1(0xc000458240, 0x2995420, 0x0, 0x0, 0x0, 0x0)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:150 +0x1627
github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute(0xc000458240, 0xc00003c1d0, 0x0, 0x0, 0xc000458240, 0xc00003c1d0)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:698 +0x42c
github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000458240, 0xc000458240, 0xc000215eb8, 0x9)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:783 +0x2c9
github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:736
main.main()
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/cmd/all-in-one/main.go:185 +0x6f7
exit status 2

```

**Comment by jpkrohling** [comment]
Turns out, this is not specific to badger.
