### ISSUE TITLE
Error (logged with the stack) when trace isn't found

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2095]
When reloading the Jaeger UI with a trace that has expired (badger, ttl=1m), the following error is recorded in the logs:

```
2020/02/27 17:01:29 http: superfluous response.WriteHeader call from github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1 (recovery.go:73)
{"level":"error","ts":1582819289.5606296,"caller":"recoveryhandler/zap.go:33","msg":"runtime error: invalid memory address or nil pointer dereference","stacktrace":"github.com/jaegertracing/jaeger/pkg/recoveryhandler.zapRecoveryWrapper.Println\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/pkg/recoveryhandler/zap.go:33\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.recoveryHandler.log\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/recovery.go:83\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/recovery.go:74\nruntime.gopanic\n\t/mnt/storage/jpkroehling/Tools/go-bin/go/src/runtime/panic.go:679\nruntime.panicmem\n\t/mnt/storage/jpkroehling/Tools/go-bin/go/src/runtime/panic.go:199\nruntime.sigpanic\n\t/mnt/storage/jpkroehling/Tools/go-bin/go/src/runtime/signal_unix.go:394\ngithub.com/jaegertracing/jaeger/model/adjuster.(*spanIDDeduper).groupSpansByID\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/model/adjuster/span_id_deduper.go:57\ngithub.com/jaegertracing/jaeger/model/adjuster.SpanIDDeduper.func1\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/model/adjuster/span_id_deduper.go:35\ngithub.com/jaegertracing/jaeger/model/adjuster.Func.Adjust\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/model/adjuster/adjuster.go:36\ngithub.com/jaegertracing/jaeger/model/adjuster.sequence.Adjust\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/model/adjuster/adjuster.go:62\ngithub.com/jaegertracing/jaeger/cmd/query/app/querysvc.QueryService.Adjust\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/cmd/query/app/querysvc/query_service.go:116\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).convertModelToUI\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:304\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).getTrace\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:385\nnet/http.HandlerFunc.ServeHTTP\n\t/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:2007\ngithub.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:140\nnet/http.HandlerFunc.ServeHTTP\n\t/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:2007\nnet/http.HandlerFunc.ServeHTTP\n\t/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:2007\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux/mux.go:212\ngithub.com/jaegertracing/jaeger/cmd/query/app.additionalHeadersHandler.func1\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/cmd/query/app/additional_headers_handler.go:28\nnet/http.HandlerFunc.ServeHTTP\n\t/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:2007\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/compress.go:148\nnet/http.HandlerFunc.ServeHTTP\n\t/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:2007\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\t/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\t/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:1890"}
goroutine 87 [running]:
runtime/debug.Stack(0x9e9962, 0xc000168600, 0xc007754000)
	/mnt/storage/jpkroehling/Tools/go-bin/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/mnt/storage/jpkroehling/Tools/go-bin/go/src/runtime/debug/stack.go:16 +0x22
github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.recoveryHandler.log(0x1df8ce0, 0xc005ae6480, 0x1df7ae0, 0xc000168600, 0x1, 0xc005adf860, 0x1, 0x1)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/recovery.go:89 +0x6e
github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1(0x1e17e00, 0xc000132700, 0x1df8ce0, 0xc005ae6480, 0x1df7ae0, 0xc000168600, 0x1)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/recovery.go:74 +0xda
panic(0x13ebe20, 0x2904570)
	/mnt/storage/jpkroehling/Tools/go-bin/go/src/runtime/panic.go:679 +0x1b2
github.com/jaegertracing/jaeger/model/adjuster.(*spanIDDeduper).groupSpansByID(0xc005d23148)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/model/adjuster/span_id_deduper.go:58 +0x48
github.com/jaegertracing/jaeger/model/adjuster.SpanIDDeduper.func1(0x0, 0x15f528c, 0xc, 0x0)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/model/adjuster/span_id_deduper.go:35 +0x4b
github.com/jaegertracing/jaeger/model/adjuster.Func.Adjust(0x1c56980, 0x0, 0x0, 0x0, 0xc000127b98)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/model/adjuster/adjuster.go:36 +0x30
github.com/jaegertracing/jaeger/model/adjuster.sequence.Adjust(0x29777a0, 0x5, 0x5, 0xc005d23200, 0x0, 0xc005ade270, 0x1, 0xc005d232e8)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/model/adjuster/adjuster.go:62 +0xa5
github.com/jaegertracing/jaeger/cmd/query/app/querysvc.QueryService.Adjust(...)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/cmd/query/app/querysvc/query_service.go:116
github.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).convertModelToUI(0xc0059eb4a0, 0x0, 0xc00745d401, 0x0, 0x0)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:304 +0x1e4
github.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).getTrace(0xc0059eb4a0, 0x1e193c0, 0xc00745d4a0, 0xc000127b00)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:385 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc005ade7d0, 0x1e193c0, 0xc00745d4a0, 0xc000127b00)
	/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:2007 +0x44
github.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5(0x1e160c0, 0xc00745d3b0, 0xc000127900)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:140 +0x5fb
net/http.HandlerFunc.ServeHTTP(0xc005adbe90, 0x1e160c0, 0xc00745d3b0, 0xc000127900)
	/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:2007 +0x44
net/http.HandlerFunc.ServeHTTP(0xc005a91c20, 0x1e160c0, 0xc00745d3b0, 0xc000127900)
	/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:2007 +0x44
github.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001c8240, 0x1e160c0, 0xc00745d3b0, 0xc005d0f100)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/jaegertracing/jaeger/cmd/query/app.additionalHeadersHandler.func1(0x1e160c0, 0xc00745d3b0, 0xc005d0f100)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/cmd/query/app/additional_headers_handler.go:28 +0x190
net/http.HandlerFunc.ServeHTTP(0xc005ae6460, 0x1e160c0, 0xc00745d3b0, 0xc005d0f100)
	/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:2007 +0x44
github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1(0x1e17e00, 0xc000132700, 0xc005d0f100)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/compress.go:148 +0x19b
net/http.HandlerFunc.ServeHTTP(0xc005ae6480, 0x1e17e00, 0xc000132700, 0xc005d0f100)
	/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:2007 +0x44
github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP(0x1df8ce0, 0xc005ae6480, 0x1df7ae0, 0xc000168600, 0x1, 0x1e17e00, 0xc000132700, 0xc005d0f100)
	/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/recovery.go:78 +0xdd
net/http.serverHandler.ServeHTTP(0xc000132380, 0x1e17e00, 0xc000132700, 0xc005d0f100)
	/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc005ea8000, 0x1e1ee80, 0xc005eaa000)
	/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/mnt/storage/jpkroehling/Tools/go-bin/go/src/net/http/server.go:2927 +0x38e
```

Steps to reproduce:

1. `$ SPAN_STORAGE_TYPE=badger go run -tags ui ./cmd/all-in-one --badger.span-store-ttl=1m`
1. http://localhost:16686, and refresh, so that a trace is available
1. open one of the available traces
1. wait a couple of minutes
1. refresh the screen
1. look at the logs

Not sure yet if Badger is relevant here.

**Comment by jpkrohling** [comment]
Duplicate of #1848, apparently.
