### ISSUE TITLE
OTEL Badger exporter fails to read/deserialize data

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#2485]
**Describe the bug**

OTEL Badger exporter fails to read/deserialize data

```
2020-09-17T14:27:25.099+0200	ERROR	recoveryhandler/zap.go:33	invalid Go type model.TraceID for field jaeger.api_v2.Span.trace_id
github.com/jaegertracing/jaeger/pkg/recoveryhandler.zapRecoveryWrapper.Println
	/home/ploffay/projects/jaegertracing/jaeger/pkg/recoveryhandler/zap.go:33
github.com/gorilla/handlers.recoveryHandler.log
	/home/ploffay/projects/golang/pkg/mod/github.com/gorilla/handlers@v1.4.2/recovery.go:83
github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1
	/home/ploffay/projects/golang/pkg/mod/github.com/gorilla/handlers@v1.4.2/recovery.go:74
runtime.gopanic
	/home/ploffay/bin/go/src/runtime/panic.go:969
google.golang.org/protobuf/internal/impl.newSingularConverter
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/convert.go:143
google.golang.org/protobuf/internal/impl.NewConverter
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/convert.go:60
google.golang.org/protobuf/internal/impl.fieldInfoForScalar
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect_field.go:234
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect.go:67
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeReflectFuncs
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect.go:36
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message.go:90
google.golang.org/protobuf/internal/impl.(*MessageInfo).init
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message.go:72
google.golang.org/protobuf/internal/impl.(*messageReflectWrapper).ProtoMethods
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect_gen.go:150
google.golang.org/protobuf/proto.protoMethods
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/proto_methods.go:18
google.golang.org/protobuf/proto.UnmarshalOptions.unmarshal
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/decode.go:80
google.golang.org/protobuf/proto.UnmarshalOptions.UnmarshalState
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/decode.go:64
github.com/golang/protobuf/proto.UnmarshalMerge
	/home/ploffay/projects/golang/pkg/mod/github.com/golang/protobuf@v1.4.2/proto/wire.go:67
github.com/golang/protobuf/proto.Unmarshal
	/home/ploffay/projects/golang/pkg/mod/github.com/golang/protobuf@v1.4.2/proto/wire.go:58
github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore.decodeValue
	/home/ploffay/projects/jaegertracing/jaeger/plugin/storage/badger/spanstore/reader.go:104
github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore.(*TraceReader).getTraces.func1
	/home/ploffay/projects/jaegertracing/jaeger/plugin/storage/badger/spanstore/reader.go:141
github.com/dgraph-io/badger.(*DB).View
	/home/ploffay/projects/golang/pkg/mod/github.com/dgraph-io/badger@v1.5.3/transaction.go:567
github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore.(*TraceReader).getTraces
	/home/ploffay/projects/jaegertracing/jaeger/plugin/storage/badger/spanstore/reader.go:123
github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore.(*TraceReader).FindTraces
	/home/ploffay/projects/jaegertracing/jaeger/plugin/storage/badger/spanstore/reader.go:462
github.com/jaegertracing/jaeger/cmd/query/app/querysvc.QueryService.FindTraces
	/home/ploffay/projects/jaegertracing/jaeger/cmd/query/app/querysvc/query_service.go:95
github.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).search
	/home/ploffay/projects/jaegertracing/jaeger/cmd/query/app/http_handler.go:222
net/http.HandlerFunc.ServeHTTP
	/home/ploffay/bin/go/src/net/http/server.go:2012
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5
	/home/ploffay/projects/golang/pkg/mod/github.com/opentracing-contrib/go-stdlib@v0.0.0-20190519235532-cf7a6c988dc9/nethttp/server.go:140
net/http.HandlerFunc.ServeHTTP
	/home/ploffay/bin/go/src/net/http/server.go:2012
net/http.HandlerFunc.ServeHTTP
	/home/ploffay/bin/go/src/net/http/server.go:2012
github.com/gorilla/mux.(*Router).ServeHTTP
	/home/ploffay/projects/golang/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210
github.com/jaegertracing/jaeger/cmd/query/app.additionalHeadersHandler.func1
	/home/ploffay/projects/jaegertracing/jaeger/cmd/query/app/additional_headers_handler.go:28
net/http.HandlerFunc.ServeHTTP
	/home/ploffay/bin/go/src/net/http/server.go:2012
github.com/gorilla/handlers.CompressHandlerLevel.func1
	/home/ploffay/projects/golang/pkg/mod/github.com/gorilla/handlers@v1.4.2/compress.go:148
net/http.HandlerFunc.ServeHTTP
	/home/ploffay/bin/go/src/net/http/server.go:2012
github.com/gorilla/handlers.recoveryHandler.ServeHTTP
	/home/ploffay/projects/golang/pkg/mod/github.com/gorilla/handlers@v1.4.2/recovery.go:78
net/http.serverHandler.ServeHTTP
	/home/ploffay/bin/go/src/net/http/server.go:2807
net/http.(*conn).serve
	/home/ploffay/bin/go/src/net/http/server.go:1895
goroutine 274 [running]:
runtime/debug.Stack(0xe1a6c2, 0xc000882840, 0xc0003ceff0)
	/home/ploffay/bin/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/home/ploffay/bin/go/src/runtime/debug/stack.go:16 +0x22
github.com/gorilla/handlers.recoveryHandler.log(0x3f5bf20, 0xc000c9c100, 0x3f5a960, 0xc000882840, 0x1, 0xc007e7c020, 0x1, 0x1)
	/home/ploffay/projects/golang/pkg/mod/github.com/gorilla/handlers@v1.4.2/recovery.go:89 +0x6e
github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1(0x3fad460, 0xc00018c9a0, 0x3f5bf20, 0xc000c9c100, 0x3f5a960, 0xc000882840, 0x1)
	/home/ploffay/projects/golang/pkg/mod/github.com/gorilla/handlers@v1.4.2/recovery.go:74 +0xda
panic(0x2bd4a80, 0xc000a8df70)
	/home/ploffay/bin/go/src/runtime/panic.go:969 +0x166
google.golang.org/protobuf/internal/impl.newSingularConverter(0x40112e0, 0x2ffba00, 0x40111c0, 0xc000897500, 0xc0001bca70, 0x30)
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/convert.go:143 +0xff5
google.golang.org/protobuf/internal/impl.NewConverter(0x40112e0, 0x2ffba00, 0x40111c0, 0xc000897500, 0x2, 0x30)
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/convert.go:60 +0xd9
google.golang.org/protobuf/internal/impl.fieldInfoForScalar(0x40111c0, 0xc000897500, 0x2dfba89, 0x7, 0x0, 0x0, 0x40112e0, 0x2ffba00, 0x2dfba92, 0x5b, ...)
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect_field.go:234 +0x110
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc(0xc00042b900, 0xe0, 0xffffffffffffffff, 0xc8, 0xffffffffffffffff, 0xc000c5a8a0, 0xc000c5a8d0, 0xc000c5a900, 0xc000c5a930)
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect.go:67 +0x938
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeReflectFuncs(0xc00042b900, 0x40112e0, 0x3295f60, 0xe0, 0xffffffffffffffff, 0xc8, 0xffffffffffffffff, 0xc000c5a8a0, 0xc000c5a8d0, 0xc000c5a900, ...)
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect.go:36 +0x63
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0xc00042b900)
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message.go:90 +0x182
google.golang.org/protobuf/internal/impl.(*MessageInfo).init(0xc00042b900)
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message.go:72 +0x3c
google.golang.org/protobuf/internal/impl.(*messageReflectWrapper).ProtoMethods(0xc000a8db70, 0xc000bbc101)
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect_gen.go:150 +0x2f
google.golang.org/protobuf/proto.protoMethods(...)
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/proto_methods.go:18
google.golang.org/protobuf/proto.UnmarshalOptions.unmarshal(0x101, 0x3f75900, 0xc0000c38f0, 0xc000b59000, 0x7dc, 0x800, 0x40034c0, 0xc000a8db70, 0x5b5e238, 0x203000, ...)
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/decode.go:80 +0x7f
google.golang.org/protobuf/proto.UnmarshalOptions.UnmarshalState(...)
	/home/ploffay/projects/golang/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/decode.go:64
github.com/golang/protobuf/proto.UnmarshalMerge(0xc000b59000, 0x7dc, 0x800, 0x3f9d6a0, 0xc000bbc1e0, 0x801, 0xc000bbc1e0)
	/home/ploffay/projects/golang/pkg/mod/github.com/golang/protobuf@v1.4.2/proto/wire.go:67 +0x19b
github.com/golang/protobuf/proto.Unmarshal(0xc000b59000, 0x7dc, 0x800, 0x3f9d6a0, 0xc000bbc1e0, 0xc0006d1000, 0x19)
	/home/ploffay/projects/golang/pkg/mod/github.com/golang/protobuf@v1.4.2/proto/wire.go:58 +0x67
github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore.decodeValue(0xc000b59000, 0x7dc, 0x800, 0x2, 0xc000b59000, 0x7dc, 0x800)
	/home/ploffay/projects/jaegertracing/jaeger/plugin/storage/badger/spanstore/reader.go:104 +0x85
github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore.(*TraceReader).getTraces.func1(0xc007d32360, 0x0, 0x0)
	/home/ploffay/projects/jaegertracing/jaeger/plugin/storage/badger/spanstore/reader.go:141 +0x1e0
github.com/dgraph-io/badger.(*DB).View(0xc000012600, 0xc0062632c0, 0x0, 0x0)
	/home/ploffay/projects/golang/pkg/mod/github.com/dgraph-io/badger@v1.5.3/transaction.go:567 +0x9d
github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore.(*TraceReader).getTraces(0xc000591190, 0xc0069663c0, 0x1, 0x14, 0xc0069663c0, 0x1, 0x14, 0x0, 0x0)
	/home/ploffay/projects/jaegertracing/jaeger/plugin/storage/badger/spanstore/reader.go:123 +0x1e4
github.com/jaegertracing/jaeger/plugin/storage/badger/spanstore.(*TraceReader).FindTraces(0xc000591190, 0x3fb8f60, 0xc000909ef0, 0xc007d32240, 0x0, 0x190, 0x203000, 0x203000, 0x1)
	/home/ploffay/projects/jaegertracing/jaeger/plugin/storage/badger/spanstore/reader.go:462 +0xb6
github.com/jaegertracing/jaeger/cmd/query/app/querysvc.QueryService.FindTraces(...)
	/home/ploffay/projects/jaegertracing/jaeger/cmd/query/app/querysvc/query_service.go:95
github.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).search(0xc000770870, 0x3faf2a0, 0xc007d378b0, 0xc0008a1500)
	/home/ploffay/projects/jaegertracing/jaeger/cmd/query/app/http_handler.go:222 +0x62b
net/http.HandlerFunc.ServeHTTP(0xc00062eb80, 0x3faf2a0, 0xc007d378b0, 0xc0008a1500)
	/home/ploffay/bin/go/src/net/http/server.go:2012 +0x44
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5(0x3f9cda0, 0xc007d377c0, 0xc0008a1300)
	/home/ploffay/projects/golang/pkg/mod/github.com/opentracing-contrib/go-stdlib@v0.0.0-20190519235532-cf7a6c988dc9/nethttp/server.go:140 +0x5d1
net/http.HandlerFunc.ServeHTTP(0xc00030c450, 0x3f9cda0, 0xc007d377c0, 0xc0008a1300)
	/home/ploffay/bin/go/src/net/http/server.go:2012 +0x44
net/http.HandlerFunc.ServeHTTP(0xc00069db40, 0x3f9cda0, 0xc007d377c0, 0xc0008a1300)
	/home/ploffay/bin/go/src/net/http/server.go:2012 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002c4480, 0x3f9cda0, 0xc007d377c0, 0xc000153700)
	/home/ploffay/projects/golang/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
github.com/jaegertracing/jaeger/cmd/query/app.additionalHeadersHandler.func1(0x3f9cda0, 0xc007d377c0, 0xc000153700)
	/home/ploffay/projects/jaegertracing/jaeger/cmd/query/app/additional_headers_handler.go:28 +0x190
net/http.HandlerFunc.ServeHTTP(0xc000c9c0e0, 0x3f9cda0, 0xc007d377c0, 0xc000153700)
	/home/ploffay/bin/go/src/net/http/server.go:2012 +0x44
github.com/gorilla/handlers.CompressHandlerLevel.func1(0x3fad460, 0xc00018c9a0, 0xc000153700)
	/home/ploffay/projects/golang/pkg/mod/github.com/gorilla/handlers@v1.4.2/compress.go:148 +0x17b
net/http.HandlerFunc.ServeHTTP(0xc000c9c100, 0x3fad460, 0xc00018c9a0, 0xc000153700)
	/home/ploffay/bin/go/src/net/http/server.go:2012 +0x44
github.com/gorilla/handlers.recoveryHandler.ServeHTTP(0x3f5bf20, 0xc000c9c100, 0x3f5a960, 0xc000882840, 0x1, 0x3fad460, 0xc00018c9a0, 0xc000153700)
	/home/ploffay/projects/golang/pkg/mod/github.com/gorilla/handlers@v1.4.2/recovery.go:78 +0xce
net/http.serverHandler.ServeHTTP(0xc00018c1c0, 0x3fad460, 0xc00018c9a0, 0xc000153700)
	/home/ploffay/bin/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc000890140, 0x3fb8ea0, 0xc000127800)
	/home/ploffay/bin/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/home/ploffay/bin/go/src/net/http/server.go:2933 +0x35c
```

**To Reproduce**
```
SPAN_STORAGE_TYPE=badger go run -tags ui ./cmd/all-in-one/main.go
```

Then open UI and refresh to generate some data from the query service. The exception should appear in logs.

**Version (please complete the following information):**

latest master

**Comment by pavolloffay** [comment]
```
invalid Go type model.TraceID for field jaeger.api_v2.Span.trace_id
```

This might be related to https://github.com/jaegertracing/jaeger/issues/2449 - bump to gRPC 0.31.0.

The OTEL module uses

```
go list -m all | grep grpc                                                  2:36 
github.com/grpc-ecosystem/go-grpc-middleware v1.2.0
github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
github.com/grpc-ecosystem/grpc-gateway v1.14.7
github.com/grpc-ecosystem/grpc-opentracing v0.0.0-20180507213350-8e809c8a8645
github.com/opentracing-contrib/go-grpc v0.0.0-20191001143057-db30781987df
github.com/tmc/grpc-websocket-proxy v0.0.0-20190109142713-0ad062ec5ee5
google.golang.org/grpc v1.31.0
google.golang.org/grpc/examples v0.0.0-20200728065043-dfc0c05b2da9

go list -m all | grep protobuf                                      2:36 
github.com/gogo/protobuf v1.3.1
github.com/golang/protobuf v1.4.2
github.com/matttproud/golang_protobuf_extensions v1.0.1
google.golang.org/protobuf v1.25.0
```

and Jaeger core
```
go list -m all | grep grpc                                                                    2:37 
github.com/grpc-ecosystem/go-grpc-middleware v1.2.0
github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
github.com/grpc-ecosystem/grpc-gateway v1.14.5
github.com/grpc-ecosystem/grpc-opentracing v0.0.0-20180507213350-8e809c8a8645
github.com/opentracing-contrib/go-grpc v0.0.0-20191001143057-db30781987df
github.com/tmc/grpc-websocket-proxy v0.0.0-20190109142713-0ad062ec5ee5
google.golang.org/grpc v1.29.1

go list -m all | grep protobuf                                                        2:36 
github.com/gogo/protobuf v1.2.1
github.com/golang/protobuf v1.3.4
github.com/matttproud/golang_protobuf_extensions v1.0.1
```

There is an inconsistency of grpc and protobuf versions.
