### ISSUE TITLE
Jaeger collector crashed 

### ISSUE THREAD

**Issue by Etienne-Carriere** [jaegertracing/jaeger#2518]
**Describe the bug**
Crash of Jaeger Collector

**To Reproduce**
Unfortunately, it happens sometimes with 1.17.0 and is more freqent with 1.18.0 so I stay in 1.17.0

**Screenshots**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x402540]

goroutine 131 [running]:
strings.Count(0x0, 0xc000150e70, 0x1454335, 0x1, 0x10)
        strings/strings.go:84 +0xf2
strings.Replace(0x0, 0xc000150e70, 0x1454335, 0x1, 0x1454342, 0x1, 0xffffffffffffffff, 0x7fff3666f6c5, 0x9)
        strings/strings.go:934 +0x9b
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel.FromDomain.convertKeyValuesString(0x13ec301, 0xc000320cc0, 0x1454342, 0x1, 0xc0007a8800, 0x14, 0x22, 0xc000f001c0, 0x10, 0x0, ...)
        github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel/from_domain.go:96 +0x1a4
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel.FromDomain.convertProcess(...)
        github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel/from_domain.go:123
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel.FromDomain.convertSpanEmbedProcess(0x70e3601, 0xc000320cc0, 0x1454342, 0x1, 0xc000d2b0e0, 0xc000572680)
        github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel/from_domain.go:64 +0x145
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel.FromDomain.FromDomainEmbedProcess(...)
        github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel/from_domain.go:43
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan(0xc000430cb0, 0xc000d2b0e0, 0x0, 0x0)
        github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:137 +0xae
github.com/jaegertracing/jaeger/storage/spanstore.(*CompositeWriter).WriteSpan(0xc0004a0a00, 0xc000d2b0e0, 0x21049e0, 0x0)
        github.com/jaegertracing/jaeger/storage/spanstore/composite.go:39 +0x9c
github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan(0xc00050c000, 0xc000d2b0e0)
        github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:143 +0x9a
github.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1(0xc000d2b0e0)
        github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:35 +0x4d
github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue(0xc00050c000, 0xc000578060)
        github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:174 +0x53
github.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1(0x118dac0, 0xc000578060)
        github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:75 +0x45
github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1(0xc0004b01a0, 0xc000493860)
        github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:77 +0xc3
created by github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers
        github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:68 +0xc0
```

**Version (please complete the following information):**
 - OS: Centos 7 
 - Jaeger version: 1.17.0 ({"gitCommit":"00985cadeb757886ac158f10e4b8229067797b65","GitVersion":"v1.17.0","BuildDate":"2020-02-24T18:55:12Z"})
 - Deployment: baremetal 

**What troubleshooting steps did you try?**
I look at the code : https://github.com/jaegertracing/jaeger/blob/v1.17.0/plugin/storage/es/spanstore/dbmodel/from_domain.go#L96
According to the 0x00 address, we can suppose it is the kv.Key that is nil but I don't understand how it is possible as the Key field in a KeyValue object is a string and so is normally initialized to "" and not nil .

**Additional context**
Starting script
```
export ES_USERNAME=
export ES_PASSWORD=
export SPAN_STORAGE_TYPE=elasticsearch,kafka
Agents are in tchannel : --reporter.tchannel.host-port=localhost:14267 
Collector have the following optinos : 
        --es.server-urls=xxx\
        --es.num-replicas=1\
        --es.tags-as-fields.all\
        --kafka.producer.brokers xxx\
        --kafka.producer.encoding json\
        --kafka.producer.topic jaeger-spans\
        --collector.tags "collector=xxx,region=yyy,az=zzz"
```

**Comment by objectiser** [comment]
@Etienne-Carriere Seems to imply a problem with the data being reported - what client/version are you using?

Even so, would be worth adding a guard (and possibly some debug logging) to prevent it from causing a panic. Would you be interested in submitting a PR?

**Comment by Etienne-Carriere** [comment]
I didn't reproduced it and now in 1.26 I don't have any issues. I close the ticket.
