### ISSUE TITLE
es-index-cleaner "ES_TLS_SKIP_HOST_VERIFY" does not work

### ISSUE THREAD

**Issue by Creator1024** [jaegertracing/jaeger#2872]
**Describe the bug**
I deploy jaeger in kubernetes with jaeger operator. 
The storage is elasticsearch which expose a tls port with self-signed certificate.
I have set skip-host-verify options in jaeger: 
```
 options:
    es:
      server-urls: https://tracing-es:9200
      index-prefix: jaeger
      tls:
        ca: /es/certificates/tls.crt
        skip-host-verify: true
  esIndexCleaner:
    image:  "jaegertracing/jaeger-es-index-cleaner:1.20.0"
    enabled: true
    numberOfDays: 7
    schedule: "01 * * * *"
```

And show cronjob I see  `ES_TLS_SKIP_HOST_VERIFY` env has been set "true"
```
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      parallelism: 1
      template:
        metadata:
          annotations:
            linkerd.io/inject: disabled
            prometheus.io/scrape: "false"
            sidecar.istio.io/inject: "false"
          creationTimestamp: null
          labels:
            app: jaeger
            app.kubernetes.io/component: cronjob-es-index-cleaner
            app.kubernetes.io/instance: jaeger
            app.kubernetes.io/managed-by: jaeger-operator
            app.kubernetes.io/name: jaeger-es-index-cleaner
            app.kubernetes.io/part-of: jaeger
        spec:
                  affinity: {}
                  containers:
                  - args:
                    - "7"
                    - https://tracing-es:9200
                    env:
                    - name: INDEX_PREFIX
                      value: jaeger
                    - name: ES_TLS_CA
                      value: /es/certificates/tls.crt
                    - name: ES_TLS_SKIP_HOST_VERIFY
                      value: "true"
                    envFrom:
                    - secretRef:
                        name: jaeger-es-secrets
                    image: jaegertracing/jaeger-es-index-cleaner:1.20.0
```

jaeger-collector can successfully connect to elasticsearch but es-index-cleaner throw exception:

```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/es-index-cleaner/esCleaner.py", line 112, in <module>
    main()
  File "/es-index-cleaner/esCleaner.py", line 30, in main
    ilo = curator.IndexList(client)
  File "/usr/local/lib/python3.8/site-packages/curator/indexlist.py", line 31, in __init__
    self.__get_indices()
  File "/usr/local/lib/python3.8/site-packages/curator/indexlist.py", line 66, in __get_indices
    self.all_indices = utils.get_indices(self.client)
  File "/usr/local/lib/python3.8/site-packages/curator/utils.py", line 653, in get_indices
    raise exceptions.FailedExecution('Failed to get indices. Error: {0}'.format(e))
curator.exceptions.FailedExecution: Failed to get indices. Error: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'tracing-es'. (_ssl.c:1124)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'tracing'. (_ssl.c:1124))
```

**Version (please complete the following information):**
 - OS: linux
 - Jaeger version: 1.20.0
 - Deployment: Kubernetes(jaeger operator)

**Comment by Creator1024** [comment]
It seemds that skipHostVerify does not work if a ca is set for ssl context? 

https://github.com/jaegertracing/jaeger/blob/6072ef2e6c00ca5a4ad6fc2515869405cd4704b8/plugin/storage/es/esCleaner.py#L102

**Comment by jpkrohling** [comment]
Did you close this issue because it's not an issue?

**Comment by Creator1024** [comment]
Thanks, it's not an issue, I have solve this problem by setting index clean policy in elasticsearch.
