### ISSUE TITLE
panic: proto: duplicate extension registered: descriptor.MethodOptions 72295728

### ISSUE THREAD

**Issue by shuxnhs** [jaegertracing/jaeger#2995]
**Describe the bug**
I am importing jaeger-tracing/jaeger and istio/client-go which each use gogo/protobuf in their underlying implementation. When I try to run my project, I get this error:
```
panic: proto: duplicate extension registered: descriptor.MethodOptions 72295728

goroutine 1 [running]:
github.com/gogo/protobuf/proto.RegisterExtension(0x434fa60)
        /Users/hexiaohong/go/src/test/vendor/github.com/gogo/protobuf/proto/extensions.go:595 +0x2d7
github.com/gogo/googleapis/google/api.init.0()
        /Users/hexiaohong/go/src/test/vendor/github.com/gogo/googleapis/google/api/annotations.pb.go:32 +0x2d
```

**Comment by jkowall** [comment]
Deprecated our instrumentation, should be using otel now.
