### ISSUE TITLE
Collector badger storage panic

### ISSUE THREAD

**Issue by yeya24** [jaegertracing/jaeger#3161]
**Describe the bug**
Our jaeger collector got OOMed and later fails to start with badger keeps crash looping and it seems that badger fails to initialize.

**Expected behavior**
Badger can initialize successfully.

**Screenshots**
```
2021/07/22 19:01:41 maxprocs: Updating GOMAXPROCS=4: determined from CPU quota
{"level":"info","ts":1626980501.846149,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1626980501.84621,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1626980501.846433,"caller":"flags/admin.go:105","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1626980501.846488,"caller":"flags/admin.go:111","msg":"Starting admin HTTP server","http-addr":":14269"}
{"level":"info","ts":1626980501.8465092,"caller":"flags/admin.go:97","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
unexpected fault address 0x7efd0fed7000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7efd0fed7000 pc=0x4734d1]

goroutine 1 [running]:
runtime.throw(0x17b4277, 0x5)
	runtime/panic.go:1117 +0x72 fp=0xc0004e8138 sp=0xc0004e8108 pc=0x4385b2
runtime.sigpanic()
	runtime/signal_unix.go:731 +0x2c8 fp=0xc0004e8170 sp=0xc0004e8138 pc=0x44fe68
runtime.memmove(0x7efd0fed7000, 0xc0006b8090, 0x14)
	runtime/memmove_amd64.s:183 +0x151 fp=0xc0004e8178 sp=0xc0004e8170 pc=0x4734d1
github.com/dgraph-io/badger/v3.(*logFile).bootstrap(0xc00000af00, 0xc00019d200, 0xc00019d200)
	github.com/dgraph-io/badger/v3@v3.2103.0/memtable.go:628 +0x1b3 fp=0xc0004e81e8 sp=0xc0004e8178 pc=0xef7693
github.com/dgraph-io/badger/v3.(*logFile).open(0xc00000af00, 0xc0006b8060, 0x15, 0x42, 0x8000000, 0x0, 0x0)
	github.com/dgraph-io/badger/v3@v3.2103.0/memtable.go:560 +0x4d6 fp=0xc0004e82a8 sp=0xc0004e81e8 pc=0xef7436
github.com/dgraph-io/badger/v3.(*DB).openMemTable(0xc000470000, 0x13b2, 0x42, 0xc00076e518, 0x50a11e, 0xc0005df640)
	github.com/dgraph-io/badger/v3@v3.2103.0/memtable.go:130 +0x24b fp=0xc0004e84c8 sp=0xc0004e82a8 pc=0xef3f4b
github.com/dgraph-io/badger/v3.(*DB).newMemTable(0xc000470000, 0xc000044015, 0xb, 0xc000040047)
	github.com/dgraph-io/badger/v3@v3.2103.0/memtable.go:153 +0x55 fp=0xc0004e8568 sp=0xc0004e84c8 pc=0xef43f5
github.com/dgraph-io/badger/v3.Open(0xc000044015, 0xb, 0xc000040047, 0xc, 0x0, 0x1, 0x0, 0x207aa80, 0xc00050f090, 0x10000000001, ...)
	github.com/dgraph-io/badger/v3@v3.2103.0/db.go:343 +0x128e fp=0xc0004e8c40 sp=0xc0004e8568 pc=0xecd94e
github.com/jaegertracing/jaeger/plugin/storage/badger.(*Factory).Initialize(0xc0001f4080, 0x207e2f8, 0xc00019bcb0, 0xc0000d6fc0, 0xc0001f4080, 0x1)
	github.com/jaegertracing/jaeger/plugin/storage/badger/factory.go:121 +0x17b fp=0xc0004e90f8 sp=0xc0004e8c40 pc=0xf2a31b
github.com/jaegertracing/jaeger/plugin/storage.(*Factory).Initialize(0xc0002ed420, 0x207e2f8, 0xc00019bcb0, 0xc0000d6fc0, 0xc0004a0000, 0xc0001445a0)
	github.com/jaegertracing/jaeger/plugin/storage/factory.go:112 +0xf5 fp=0xc0004e9198 sp=0xc0004e90f8 pc=0x1345595
main.main.func1(0xc0003e8000, 0xc00050f530, 0x0, 0x1, 0x0, 0x0)
	command-line-arguments/main.go:102 +0x2dc fp=0xc0004e9c40 sp=0xc0004e9198 pc=0x13f1a5c
github.com/spf13/cobra.(*Command).execute(0xc0003e8000, 0xc00018c010, 0x1, 0x1, 0xc0003e8000, 0xc00018c010)
	github.com/spf13/cobra@v0.0.7/command.go:838 +0x472 fp=0xc0004e9d00 sp=0xc0004e9c40 pc=0x7af592
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003e8000, 0xc0003e8000, 0xc00063fee0, 0x9)
	github.com/spf13/cobra@v0.0.7/command.go:943 +0x336 fp=0xc0004e9de0 sp=0xc0004e9d00 pc=0x7b00d6
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.7/command.go:883
main.main()
	command-line-arguments/main.go:216 +0x806 fp=0xc0004e9f88 sp=0xc0004e9de0 pc=0x13efd46
runtime.main()
	runtime/proc.go:225 +0x256 fp=0xc0004e9fe0 sp=0xc0004e9f88 pc=0x43adf6
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc0004e9fe8 sp=0xc0004e9fe0 pc=0x472581

goroutine 19 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x2a13f40)
	github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x274

goroutine 49 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000122340)
	github.com/klauspost/compress@v1.12.2/zstd/blockdec.go:215 +0x149
created by github.com/klauspost/compress/zstd.newBlockDec
	github.com/klauspost/compress@v1.12.2/zstd/blockdec.go:118 +0x173

goroutine 50 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000122410)
	github.com/klauspost/compress@v1.12.2/zstd/blockdec.go:215 +0x149
created by github.com/klauspost/compress/zstd.newBlockDec
	github.com/klauspost/compress@v1.12.2/zstd/blockdec.go:118 +0x173

goroutine 51 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc0001224e0)
	github.com/klauspost/compress@v1.12.2/zstd/blockdec.go:215 +0x149
created by github.com/klauspost/compress/zstd.newBlockDec
	github.com/klauspost/compress@v1.12.2/zstd/blockdec.go:118 +0x173

goroutine 52 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc0001225b0)
	github.com/klauspost/compress@v1.12.2/zstd/blockdec.go:215 +0x149
created by github.com/klauspost/compress/zstd.newBlockDec
	github.com/klauspost/compress@v1.12.2/zstd/blockdec.go:118 +0x173

goroutine 8 [syscall]:
os/signal.signal_recv(0x0)
	runtime/sigqueue.go:168 +0xa5
os/signal.loop()
	os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x45

goroutine 54 [IO wait]:
internal/poll.runtime_pollWait(0x7efd1a91bee0, 0x72, 0x0)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0001f4298, 0x72, 0x0, 0x0, 0x17b6a81)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0001f4280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc0001f4280, 0x30, 0x30, 0x7efd415e8a68)
	net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc00012e8b8, 0xc0004d4d48, 0x40e2f8, 0x30)
	net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00012e8b8, 0x169cc20, 0xc00027e3f0, 0x1569700, 0x29ea330)
	net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc0001ec380, 0x2074430, 0xc00012e8b8, 0x0, 0x0)
	net/http/server.go:2981 +0x285
github.com/jaegertracing/jaeger/cmd/flags.(*AdminServer).serveWithListener.func1(0xc0000e7bf0, 0x2074430, 0xc00012e8b8)
	github.com/jaegertracing/jaeger/cmd/flags/admin.go:113 +0x65
created by github.com/jaegertracing/jaeger/cmd/flags.(*AdminServer).serveWithListener
	github.com/jaegertracing/jaeger/cmd/flags/admin.go:112 +0x3d7

goroutine 70 [select]:
github.com/uber/jaeger-client-go/utils.(*reconnectingUDPConn).reconnectLoop(0xc0002edea0, 0x6fc23ac00)
	github.com/uber/jaeger-client-go@v2.29.1+incompatible/utils/reconnecting_udp_conn.go:70 +0xc8
created by github.com/uber/jaeger-client-go/utils.newReconnectingUDPConn
	github.com/uber/jaeger-client-go@v2.29.1+incompatible/utils/reconnecting_udp_conn.go:60 +0x10c

goroutine 71 [select]:
github.com/uber/jaeger-client-go.(*remoteReporter).processQueue(0xc000184780)
	github.com/uber/jaeger-client-go@v2.29.1+incompatible/reporter.go:296 +0xfe
created by github.com/uber/jaeger-client-go.NewRemoteReporter
	github.com/uber/jaeger-client-go@v2.29.1+incompatible/reporter.go:237 +0x1a5

goroutine 9 [select]:
github.com/dgraph-io/badger/v3/y.(*WaterMark).process(0xc000354960, 0xc000354900)
	github.com/dgraph-io/badger/v3@v3.2103.0/y/watermark.go:214 +0x2ab
created by github.com/dgraph-io/badger/v3/y.(*WaterMark).Init
	github.com/dgraph-io/badger/v3@v3.2103.0/y/watermark.go:72 +0x76

goroutine 10 [select]:
github.com/dgraph-io/badger/v3/y.(*WaterMark).process(0xc0003549f0, 0xc000354900)
	github.com/dgraph-io/badger/v3@v3.2103.0/y/watermark.go:214 +0x2ab
created by github.com/dgraph-io/badger/v3/y.(*WaterMark).Init
	github.com/dgraph-io/badger/v3@v3.2103.0/y/watermark.go:72 +0x76

goroutine 11 [select]:
github.com/dgraph-io/ristretto/z.(*AllocatorPool).freeupAllocators(0xc00019df68)
	github.com/dgraph-io/ristretto@v0.1.0/z/allocator.go:385 +0x145
created by github.com/dgraph-io/ristretto/z.NewAllocatorPool
	github.com/dgraph-io/ristretto@v0.1.0/z/allocator.go:324 +0xae

goroutine 22 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc000348000)
	github.com/dgraph-io/ristretto@v0.1.0/policy.go:102 +0xa5
created by github.com/dgraph-io/ristretto.newDefaultPolicy
	github.com/dgraph-io/ristretto@v0.1.0/policy.go:86 +0x129

goroutine 34 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc0000e8180)
	github.com/dgraph-io/ristretto@v0.1.0/cache.go:452 +0x158
created by github.com/dgraph-io/ristretto.NewCache
	github.com/dgraph-io/ristretto@v0.1.0/cache.go:207 +0x308

goroutine 35 [select]:
github.com/dgraph-io/badger/v3.(*DB).monitorCache(0xc000470000, 0xc000354ff0)
	github.com/dgraph-io/badger/v3@v3.2103.0/db.go:474 +0x17d
created by github.com/dgraph-io/badger/v3.Open
	github.com/dgraph-io/badger/v3@v3.2103.0/db.go:316 +0x8c6

goroutine 36 [select]:
github.com/dgraph-io/badger/v3.(*DB).updateSize(0xc000470000, 0xc0003557d0)
	github.com/dgraph-io/badger/v3@v3.2103.0/db.go:1176 +0x135
created by github.com/dgraph-io/badger/v3.Open
	github.com/dgraph-io/badger/v3@v3.2103.0/db.go:336 +0xa7e
```

**Version (please complete the following information):**
 - OS: Debian 9
 - Jaeger version: 1.24 jaeger all in one
 - Deployment: Kubernetes

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**

**Comment by Ashmita152** [comment]
Hi @yeya24 

Thank you for reporting the issue. 

I came across a similar thread in dgraph's forum: https://discuss.dgraph.io/t/unexpected-fault-address-error-on-one-of-the-pods/13670

As raised in that thread, may I ask if you can check the available disk space in the partition where badger is storing the data. Looking at the code https://github.com/dgraph-io/badger/blob/v3.2103.0/memtable.go#L628  it seems like it fails while copying the data to memory mapped files.

**Comment by yeya24** [comment]
Thanks @Ashmita152. After increasing the pvc size, panic disappears.
