### ISSUE TITLE
pkg/codec breaks older protobuf-generated code in grpc plugin

### ISSUE THREAD

**Issue by holycheater** [jaegertracing/jaeger#3239]
**Describe the bug**
pkg/gogocodec breaks using older protobuf (generated with versions from `github.com/golang/protobuf`) in grpc plugins.

https://github.com/jaegertracing/jaeger/blob/master/pkg/gogocodec/codec.go#L23
It uses `google.golang.org/protobuf` marshal/unmarshal where standard grpc codec (https://github.com/grpc/grpc-go/blob/v1.39.0/encoding/proto/proto.go) uses `github.com/golang/protobuf` for compatibility

I propose using same behavior in `gogocodec`.
Another more lengthy option would be explicitly using `grpc.ForceCodec(...)` and `grpc.WithDefaultCallOption(grpc.ForceCodec(...)` for server and client respectively

Example stacktrace from a storage plugin:
```
panic: interface conversion: *Ydb_Discovery.ListEndpointsRequest is not protoreflect.ProtoMessage: missing method ProtoReflect

goroutine 1 [running]:
github.com/jaegertracing/jaeger/pkg/gogocodec.(*gogoCodec).Marshal(0x1771108, 0xf5c480, 0xc0001306e0, 0x0, 0x0, 0xfe1876, 0xe, 0xfdf67f)
	/build/vendor/github.com/jaegertracing/jaeger/pkg/gogocodec/codec.go:57 +0x126
google.golang.org/grpc.encode(0x7fe7b6596258, 0x1771108, 0xf5c480, 0xc0001306e0, 0x7fe7b67fb910, 0x8, 0x18, 0x7fe7dd48c108, 0x18)
	/build/vendor/google.golang.org/grpc/rpc_util.go:594 +0x52
google.golang.org/grpc.prepareMsg(0xf5c480, 0xc0001306e0, 0x7fe7b6596258, 0x1771108, 0x0, 0x0, 0x0, 0x0, 0xd9b13e, 0xed7a40, ...)
	/build/vendor/google.golang.org/grpc/stream.go:1590 +0x10f
google.golang.org/grpc.(*clientStream).SendMsg(0xc000133560, 0xf5c480, 0xc0001306e0, 0x0, 0x0)
	/build/vendor/google.golang.org/grpc/stream.go:771 +0x165
google.golang.org/grpc.invoke(0x1114f58, 0xc0002c4a20, 0x1006046, 0x30, 0xf5c480, 0xc0001306e0, 0xf4d480, 0xc0002c49c0, 0xc00035b180, 0xc000120bc0, ...)
	/build/vendor/google.golang.org/grpc/call.go:70 +0xe7
google.golang.org/grpc.(*ClientConn).Invoke(0xc00035b180, 0x1114f58, 0xc0002c4a20, 0x1006046, 0x30, 0xf5c480, 0xc0001306e0, 0xf4d480, 0xc0002c49c0, 0x0, ...)
	/build/vendor/google.golang.org/grpc/call.go:37 +0x1b3
github.com/yandex-cloud/ydb-go-sdk/v2.invoke(0x1114f58, 0xc0002c4a20, 0xc00035b180, 0x1119700, 0xc0004a7650, 0x1006046, 0x30, 0x11102b0, 0xc0001306e0, 0x1110310, ...)
	/build/vendor/github.com/yandex-cloud/ydb-go-sdk/v2/driver.go:439 +0xfa
github.com/yandex-cloud/ydb-go-sdk/v2.(*discoveryClient).Discover(0xc00051b498, 0x1114f58, 0xc0002c4a20, 0xc000044129, 0x1f, 0xc00012c400, 0x0, 0x0, 0x0, 0x0, ...)
	/build/vendor/github.com/yandex-cloud/ydb-go-sdk/v2/discovery.go:41 +0x22c
github.com/yandex-cloud/ydb-go-sdk/v2.(*dialer).discover(0xc000128400, 0x1114f20, 0xc0001151a0, 0xc0000440fc, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/vendor/github.com/yandex-cloud/ydb-go-sdk/v2/dialer.go:271 +0x27e
github.com/yandex-cloud/ydb-go-sdk/v2.(*dialer).dial(0xc000128400, 0x1114f20, 0xc0001151a0, 0xc0000440fc, 0x16, 0x0, 0x0, 0x0, 0x0)
	/build/vendor/github.com/yandex-cloud/ydb-go-sdk/v2/dialer.go:125 +0x39c
github.com/yandex-cloud/ydb-go-sdk/v2.(*Dialer).Dial(0xc0003fde60, 0x1114f20, 0xc0001151a0, 0xc0000440fc, 0x16, 0xc0004a70b0, 0xc000125100, 0x4, 0x4)
	/build/vendor/github.com/yandex-cloud/ydb-go-sdk/v2/dialer.go:83 +0x2e5
github.com/yandex-cloud/jaeger-ydb-store/plugin.(*YdbStorage).initDB(0xc0003101e0, 0xc0001ae180)
	/build/plugin/plugin.go:132 +0xf5
github.com/yandex-cloud/jaeger-ydb-store/plugin.(*YdbStorage).InitFromViper(0xc0003101e0, 0xc0001ae180)
	/build/plugin/plugin.go:95 +0xa6d
main.main()
	/build/main.go:41 +0x5f
```

**Comment by yurishkuro** [comment]
`github.com/golang/protobuf/proto` is deprecated, we're not going back to it. What do you mean by "pkg/gogocodec breaks using older protobuf"? It doesn't break in our repo, so where does it break?

**Comment by holycheater** [comment]
It breaks in grpc storage plugin when you use any grpc client with protobuf generated through older protoc-gen-go. Because it globally overrides default grpc codec behavior as soon as jaeger plugin sdk is imported

Basically, using any grpc client/server with older protobuf will break things on the plugin side

**Comment by holycheater** [comment]
@yurishkuro I can make a PR that drops overriding default grpc proto codec with grpc `ForceCodec` for server/clients for agent/collector and plugin client/server if you're ok with that

**Comment by yurishkuro** [comment]
Why not recompile plug-ins with new proto?

**Comment by holycheater** [comment]
This proto is not part of the plugin, it's from another SDK, it will be updated there eventually, but I don't know when.
Making Jaeger not changing grpc behavior globally seemed like an easier choice
