### ISSUE TITLE
 (interface conversion: interface {} is map[string]interface {}, not string)

### ISSUE THREAD

**Issue by tirelibirefe** [jaegertracing/jaeger#3601]
**Describe the bug**

**To Reproduce**
1.  Using EKS Kubernetes 1.21

```
helm upgrade --install jaeger-operator jaegertracing/jaeger-operator -n jaeger-operator \
  --create-namespace \
  --set 'extraEnv[0].name=LOG-LEVEL' \
  --set 'extraEnv[0].value=debug' \
  --set rbac.create=true \
  --set rbac.clusterRole=true
```

3.
Try to Install a Jaeger

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: jaeger
spec:
  strategy: streaming
  ingester:
    maxReplicas: 5
    strategy:
      type: RollingUpdate
      rollingUpdate: 
        maxSurge: 50%
    resources:
      limits:
        memory: 128Mi
        cpu: 500m
    options:
      metrics-backend: prometheus
      metrics-http-route: /metrics
      log-level: info
      kafka:
        consumer:
          client-id: jaeger-ingester
          group-id: jaeger-ingester
          encoding: json
          topic: jaeger-spans
          brokers: kuap-kafka-bootstrap.kafka.svc.cluster.local:9093
          authentication: tls
          tls:
            enabled: true
            ca: /kafka/user-certificates/kafkauser-ca.crt
            cert: /kafka/user-certificates/kafkauser-user.crt
            key: /kafka/user-certificates/kafkauser-user.key
            skip-host-verify: true
      ingester:
        deadlockInterval: 0
  collector:
    maxReplicas: 5
    strategy:
      type: RollingUpdate
      rollingUpdate: 
        maxSurge: 50%
    options:
...
```

4.

The operator crashes and produces the following error message:

```
E0327 19:57:43.662130       1 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x188a5c0), concrete:(*runtime._type)(0x18abce0), asserted:(*runtime._type)(0x183ab00), missingMethod:""} (interface conversion: interface {} is map[string]interface {}, not string)
goroutine 329 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x18ce600, 0xc00070b920)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/runtime/runtime.go:48 +0x86
panic(0x18ce600, 0xc00070b920)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/jaegertracing/jaeger-operator/apis/v1.entry(0xc00070b8f0, 0xc0004ef800, 0x3, 0x17f8240, 0xc0000b7848, 0xc00070b8f0)
        /workspace/apis/v1/options.go:104 +0x5bf
github.com/jaegertracing/jaeger-operator/apis/v1.(*Options).parse(0xc000263700, 0xc00070b800)
        /workspace/apis/v1/options.go:91 +0xef
github.com/jaegertracing/jaeger-operator/apis/v1.(*Options).UnmarshalJSON(0xc000263700, 0xc000bac600, 0x1ef, 0x200, 0xc000263700, 0x183ae00)
        /workspace/apis/v1/options.go:66 +0x178
github.com/json-iterator/go.(*unmarshalerDecoder).Decode(0xc0007a74d0, 0xc0000c3488, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_marshaler.go:199 +0xb3
github.com/json-iterator/go.(*referenceDecoder).Decode(0xc0007a74e0, 0xc000263700, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_optional.go:128 +0x68
github.com/json-iterator/go.(*placeholderDecoder).Decode(0xc0007a74c0, 0xc000263700, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect.go:324 +0x47
github.com/json-iterator/go.(*structFieldDecoder).Decode(0xc000690e60, 0xc0002636d0, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:1054 +0x78
github.com/json-iterator/go.(*generalStructDecoder).decodeOneField(0xc000691080, 0xc0002636d0, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:552 +0x24c
github.com/json-iterator/go.(*generalStructDecoder).Decode(0xc000691080, 0xc0002636d0, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:508 +0x85
github.com/json-iterator/go.(*structFieldDecoder).Decode(0xc0006ce480, 0xc000263518, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:1054 +0x78
github.com/json-iterator/go.(*generalStructDecoder).decodeOneField(0xc0006ce620, 0xc000263518, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:552 +0x24c
github.com/json-iterator/go.(*generalStructDecoder).Decode(0xc0006ce620, 0xc000263518, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:508 +0x85
github.com/json-iterator/go.(*structFieldDecoder).Decode(0xc0006cf2c0, 0xc000263400, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:1054 +0x78
github.com/json-iterator/go.(*fiveFieldsStructDecoder).Decode(0xc000406480, 0xc000263400, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:735 +0x35d
github.com/json-iterator/go.(*Iterator).ReadVal(0xc0004d8630, 0x1a7d380, 0xc000263400)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect.go:79 +0xc2
github.com/json-iterator/go.(*frozenConfig).Unmarshal(0xc000163180, 0xc000784a00, 0x22b9, 0x2500, 0x1a7d380, 0xc000263400, 0x0, 0x0)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/config.go:348 +0xb7
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode(0xc00009b1d0, 0xc000784a00, 0x22b9, 0x2500, 0x0, 0x0, 0x0, 0x12421c7, 0xc00009b1d0, 0xc0007fa000, ...)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/runtime/serializer/json/json.go:264 +0x5be
k8s.io/apimachinery/pkg/runtime.WithoutVersionDecoder.Decode(0x1d0bda0, 0xc00009b1d0, 0xc000784a00, 0x22b9, 0x2500, 0x0, 0x0, 0x0, 0x1d09f00, 0x38, ...)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/runtime/helper.go:252 +0x97
k8s.io/apimachinery/pkg/runtime.Decode(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/runtime/codec.go:58
k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc0001de300, 0xc00024ff72, 0x2, 0x3, 0x1000, 0x0, 0x2)
        /go/pkg/mod/k8s.io/client-go@v0.21.2/rest/watch/decoder.go:62 +0x18c
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc0001ce540)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/watch/streamwatcher.go:105 +0xe5
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
        /go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/watch/streamwatcher.go:76 +0xea
panic: interface conversion: interface {} is map[string]interface {}, not string [recovered]
        panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 329 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/runtime/runtime.go:55 +0x109
panic(0x18ce600, 0xc00070b920)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/jaegertracing/jaeger-operator/apis/v1.entry(0xc00070b8f0, 0xc0004ef800, 0x3, 0x17f8240, 0xc0000b7848, 0xc00070b8f0)
        /workspace/apis/v1/options.go:104 +0x5bf
github.com/jaegertracing/jaeger-operator/apis/v1.(*Options).parse(0xc000263700, 0xc00070b800)
        /workspace/apis/v1/options.go:91 +0xef
github.com/jaegertracing/jaeger-operator/apis/v1.(*Options).UnmarshalJSON(0xc000263700, 0xc000bac600, 0x1ef, 0x200, 0xc000263700, 0x183ae00)
        /workspace/apis/v1/options.go:66 +0x178
github.com/json-iterator/go.(*unmarshalerDecoder).Decode(0xc0007a74d0, 0xc0000c3488, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_marshaler.go:199 +0xb3
github.com/json-iterator/go.(*referenceDecoder).Decode(0xc0007a74e0, 0xc000263700, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_optional.go:128 +0x68
github.com/json-iterator/go.(*placeholderDecoder).Decode(0xc0007a74c0, 0xc000263700, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect.go:324 +0x47
github.com/json-iterator/go.(*structFieldDecoder).Decode(0xc000690e60, 0xc0002636d0, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:1054 +0x78
github.com/json-iterator/go.(*generalStructDecoder).decodeOneField(0xc000691080, 0xc0002636d0, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:552 +0x24c
github.com/json-iterator/go.(*generalStructDecoder).Decode(0xc000691080, 0xc0002636d0, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:508 +0x85
github.com/json-iterator/go.(*structFieldDecoder).Decode(0xc0006ce480, 0xc000263518, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:1054 +0x78
github.com/json-iterator/go.(*generalStructDecoder).decodeOneField(0xc0006ce620, 0xc000263518, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:552 +0x24c
github.com/json-iterator/go.(*generalStructDecoder).Decode(0xc0006ce620, 0xc000263518, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:508 +0x85
github.com/json-iterator/go.(*structFieldDecoder).Decode(0xc0006cf2c0, 0xc000263400, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:1054 +0x78
github.com/json-iterator/go.(*fiveFieldsStructDecoder).Decode(0xc000406480, 0xc000263400, 0xc0004d8630)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect_struct_decoder.go:735 +0x35d
github.com/json-iterator/go.(*Iterator).ReadVal(0xc0004d8630, 0x1a7d380, 0xc000263400)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/reflect.go:79 +0xc2
github.com/json-iterator/go.(*frozenConfig).Unmarshal(0xc000163180, 0xc000784a00, 0x22b9, 0x2500, 0x1a7d380, 0xc000263400, 0x0, 0x0)
        /go/pkg/mod/github.com/json-iterator/go@v1.1.12/config.go:348 +0xb7
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode(0xc00009b1d0, 0xc000784a00, 0x22b9, 0x2500, 0x0, 0x0, 0x0, 0x12421c7, 0xc00009b1d0, 0xc0007fa000, ...)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/runtime/serializer/json/json.go:264 +0x5be
k8s.io/apimachinery/pkg/runtime.WithoutVersionDecoder.Decode(0x1d0bda0, 0xc00009b1d0, 0xc000784a00, 0x22b9, 0x2500, 0x0, 0x0, 0x0, 0x1d09f00, 0x38, ...)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/runtime/helper.go:252 +0x97
k8s.io/apimachinery/pkg/runtime.Decode(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/runtime/codec.go:58
k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc0001de300, 0xc00024ff72, 0x2, 0x3, 0x1000, 0x0, 0x2)
        /go/pkg/mod/k8s.io/client-go@v0.21.2/rest/watch/decoder.go:62 +0x18c
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc0001ce540)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/watch/streamwatcher.go:105 +0xe5
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
        /go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/watch/streamwatcher.go:76 +0xea
```
When I remove "Jaeger instance"  `k delete -f jaeger.yaml`, the operator turns back to normal.

**Comment by tirelibirefe** [comment]
If I disable following env variables, it works.

```
      # env:
      # - name: COLLECTOR_ZIPKIN_HOST_PORT
      #   value: :9411
```

**Comment by tirelibirefe** [comment]
if I add following sections, the operator crashes:

```
    # ui:
    # options:
    #   dependencies:
    #     menuEnabled: false
    #   tracking:
    #     gaID: UA-000000-2
    #   menu:
    #   - label: "About Jaeger"
    #     items:
    #       - label: "Documentation"
    #         url: "https://www.jaegertracing.io/docs/latest"
    #   linkPatterns:
    #   - type: "logs"
    #     key: "customer_id"
    #     url: /search?limit=20&lookback=1h&service=frontend&tags=%7B%22customer_id%22%3A%22#{customer_id}%22%7D
    #     text: "Search for other traces for customer_id=#{customer_id}"
```

If I disable ui settings block, it works as expected.
