### ISSUE TITLE
panic receiving spans from an otlptrace.Exporter over gRPC

### ISSUE THREAD

**Issue by rosstimothy** [jaegertracing/jaeger#3717]
**Describe the bug**

```bash
tracing-jaeger-all-in-one-1  | panic: interface conversion: *v1.ExportTraceServiceRequest is not protoreflect.ProtoMessage: missing method ProtoReflect
tracing-jaeger-all-in-one-1  |
tracing-jaeger-all-in-one-1  | goroutine 143 [running]:
tracing-jaeger-all-in-one-1  | github.com/jaegertracing/jaeger/pkg/gogocodec.(*gogoCodec).Unmarshal(0x14d3580?, {0xc000400000, 0x76ca, 0x76ca}, {0x1667da0?, 0xc0002a6120})
tracing-jaeger-all-in-one-1  | 	github.com/jaegertracing/jaeger/pkg/gogocodec/codec.go:68 +0xb3
tracing-jaeger-all-in-one-1  | google.golang.org/grpc.(*Server).processUnaryRPC.func2({0x1667da0?, 0xc0002a6120})
tracing-jaeger-all-in-one-1  | 	google.golang.org/grpc@v1.46.2/server.go:1260 +0x20b
tracing-jaeger-all-in-one-1  | go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/trace/v1._TraceService_Export_Handler({0x14b5f20?, 0xc0004d6810}, {0x1ea21a8, 0xc000346720}, 0xc000290780, 0xc00008acc0)
tracing-jaeger-all-in-one-1  | 	go.opentelemetry.io/collector/pdata@v0.52.0/internal/data/protogen/collector/trace/v1/trace_service.pb.go:205 +0x63
tracing-jaeger-all-in-one-1  | google.golang.org/grpc.(*Server).processUnaryRPC(0xc00055c000, {0x1ea9478, 0xc0001b6340}, 0xc0000e8000, 0xc0002fd1a0, 0x2968f90, 0x0)
tracing-jaeger-all-in-one-1  | 	google.golang.org/grpc@v1.46.2/server.go:1283 +0xcfd
tracing-jaeger-all-in-one-1  | google.golang.org/grpc.(*Server).handleStream(0xc00055c000, {0x1ea9478, 0xc0001b6340}, 0xc0000e8000, 0x0)
tracing-jaeger-all-in-one-1  | 	google.golang.org/grpc@v1.46.2/server.go:1620 +0xa1b
tracing-jaeger-all-in-one-1  | google.golang.org/grpc.(*Server).serveStreams.func1.2()
tracing-jaeger-all-in-one-1  | 	google.golang.org/grpc@v1.46.2/server.go:922 +0x98
tracing-jaeger-all-in-one-1  | created by google.golang.org/grpc.(*Server).serveStreams.func1
tracing-jaeger-all-in-one-1  | 	google.golang.org/grpc@v1.46.2/server.go:920 +0x28a
```

**To Reproduce**
1. Create an [OTLP exporter](https://go.opentelemetry.io/otel/exporters/otlp/otlptrace) that is configured to write to jaeger grpc/http OTLP endpoints
2. Export spans with the exporter
3. jaeger panics

**Expected behavior**
jaeger is capable of unmarshalling spans received from an OTLP exporter

**Version (please complete the following information):**
 - OS: linux
 - Jaeger version: 1.35
 - Deployment: docker all in one

**Comment by yurishkuro** [comment]
To which port are you sending the data?

**Comment by yurishkuro** [comment]
Found the issue, thanks for reporting.

**Comment by yurishkuro** [comment]
please try again with 1.35.1
