### ISSUE TITLE
[Bug]: TestExtractor_TraceOutputFileError testcases fail on Power

### ISSUE THREAD

**Issue by BhimraoPatil** [jaegertracing/jaeger#4132]
### What happened?

Tests in uiconv module failing on ppc64le due to panic: runtime error: invalid memory address or nil pointer dereference
[Power_Logs.txt](https://github.com/jaegertracing/jaeger/files/10336271/Power_Logs.txt)

 

### Steps to reproduce

git clone https://github.com/jaegertracing/jaeger.git
cd jaeger
git checkout v1.40.0
go install
go test -v ./...

### Expected behavior

Any Information regarding the same will be helpful. Thanks

### Relevant log output

```shell
--- FAIL: TestExtractor_TraceOutputFileError (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x3717c4]

goroutine 20 [running]:
testing.tRunner.func1.2({0x3c5680, 0x714070})
	/usr/local/go/src/testing/testing.go:1396 +0x1fc
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1399 +0x364
panic({0x3c5680, 0x714070})
	/usr/local/go/src/runtime/panic.go:884 +0x240
github.com/jaegertracing/jaeger/cmd/anonymizer/app/uiconv.TestExtractor_TraceOutputFileError(0x0?)
	/jaeger/cmd/anonymizer/app/uiconv/extractor_test.go:86 +0x344
testing.tRunner(0xc0001b91e0, 0x45f318)
	/usr/local/go/src/testing/testing.go:1446 +0x11c
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x36c
FAIL	github.com/jaegertracing/jaeger/cmd/anonymizer/app/uiconv	0.374s
```

**Comment by jkowall** [comment]
ppc64le which run on IBM POWER8 are end of support going into 2024. I do not see this one being addressed.
