### ISSUE TITLE
[test]: panic: Log in goroutine after ... has completed: Starting main loop

### ISSUE THREAD

**Issue by kennyaz** [jaegertracing/jaeger#4576]
### What happened?

panic: Log in goroutine after ... has completed:  Starting main loop

### Steps to reproduce

Not Applicable

### Expected behavior

There is a possibility that the [goroutine](https://github.com/jaegertracing/jaeger/blob/main/cmd/ingester/app/consumer/consumer.go#L79) is not finished when [Close ](https://github.com/jaegertracing/jaeger/blob/main/cmd/ingester/app/consumer/consumer.go#L94)is called since there is no waitGroup that is waiting for the `c.logger.Info("Starting main loop")` to be done executing before the application is shutdown

### Relevant log output

```shell
panic: Log in goroutine after ... has completed:  Starting main loop

goroutine 39 [running]:
testing.(*common).logDepth(0xc00052bd40, {0xc0001b95f0, 0x30}, 0x3)
        GOROOT/src/testing/testing.go:1003 +0x4e7
testing.(*common).log(...)
        GOROOT/src/testing/testing.go:985
testing.(*common).Logf(0xc00052bd40, {0x5e4ddb?, 0x14aceb7?}, {0xc0000401c0?, 0xffffffffffffffff?, 0x31?})
        GOROOT/src/testing/testing.go:1036 +0x5a
go.uber.org/zap/zaptest.testingWriter.Write({{0x8eecf0?, 0xc00052bd40?}, 0x0?}, {0xc000241400?, 0x31, 0xc0000401b0?})
        external/org_uber_go_zap/zaptest/logger.go:130 +0xe6
go.uber.org/zap/zapcore.(*ioCore).Write(0xc0001cd860, {0x0, {0xc1233bb7a60da4ca, 0x1863da2, 0x2bf1e00}, {0x0, 0x0}, {0x5fa77a, 0x12}, {0x0, ...}, ...}, ...)
        external/org_uber_go_zap/zapcore/core.go:99 +0xb5
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0001b71e0, {0x0, 0x0, 0x0})
        external/org_uber_go_zap/zapcore/entry.go:255 +0x1d9
go.uber.org/zap.(*Logger).Info(0x0?, {0x5fa77a?, 0x0?}, {0x0, 0x0, 0x0})
        external/org_uber_go_zap/logger.go:220 +0x59
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start.func1()
        external/com_github_jaegertracing_jaeger/cmd/ingester/app/consumer/consumer.go:79 +0x4b
created by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start
        external/com_github_jaegertracing_jaeger/cmd/ingester/app/consumer/consumer.go:78 +0x6a
```

**Comment by yurishkuro** [comment]
which test is that?
