### ISSUE TITLE
Explicit declaration of hostnames and IP addresses

### ISSUE THREAD

**Issue by huntc** [jaegertracing/jaeger#742]
When using Jaeger from within an LXC container on some Cisco equipment, Jaeger complains of not being able to resolve its hostname to an address.

I was wondering if it'd be useful to provide an additional Tracer `Builder` property so that the IP address to record can be declared.

Here's the error I'm presently getting:

```
2018-03-16T06:31:16.759Z 192.168.1.3 ERROR Tracer - Cannot obtain host name
java.net.UnknownHostException: IR829-GOS-1: IR829-GOS-1: Name does not resolve
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at com.uber.jaeger.Tracer.getHostName(Tracer.java:582)
	at com.uber.jaeger.Tracer.<init>(Tracer.java:97)
	at com.uber.jaeger.Tracer.<init>(Tracer.java:58)
	at com.uber.jaeger.Tracer$Builder.build(Tracer.java:532)
	at com.uber.jaeger.Configuration.getTracer(Configuration.java:241)
	at com.github.huntc.lora.server.Server$$anon$1.preStart(Server.scala:99)
	at akka.actor.Actor.aroundPreStart(Actor.scala:528)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
	at com.github.huntc.lora.server.Server$$anon$1.aroundPreStart(Server.scala:69)
	at akka.actor.ActorCell.create(ActorCell.scala:591)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.net.UnknownHostException: IR829-GOS-1: Name does not resolve
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 19 common frames omitted
```

**Comment by yurishkuro** [comment]
We could approach it differently. Jaeger already allows the user to specify tracer tags on construction. The host name and ip are internally also added to the tags. So we could make the last part optional, ie not attempt to override the tags that are already set.

**Comment by huntc** [comment]
Sounds reasonable. Resolving hosts within toolkits almost never ends well. :-)

**Comment by yurishkuro** [comment]
Do you want to spike a PR? Should be a simple change.

**Comment by huntc** [comment]
Sure thing - I'll try and get to this in the next few days. Thanks.

**Comment by huntc** [comment]
@yurishkuro I didn't realise that this issue was in the wrong place. Regardless, I've now put together a WIP PR - https://github.com/jaegertracing/jaeger-client-java/pull/371 - please let me know if this is what you had in mind.
